.general:
  tags:
    - docker
    - linux
    - ansible
    - swarm

variables:
  DOCKER_REGISTRY: 'cm-registry.ccveu.local:5000'
  CCTP_REGISTRY: 'cm-registry.ccveu.local:5002'
  BUILD_TAG: '0.5.0'
  BUILD_VERSION: "latest"
  GIT_SUBMODULE_STRATEGY: recursive

image: ${DOCKER_REGISTRY}/cm/docker-gitlab-images/gitlab-dind-make:latest

build:
  stage: build
  script:
    - echo "Branch ${CI_COMMIT_REF_NAME}"
    - echo "Tag ${CI_COMMIT_TAG}"
    - docker build -t ${CCTP_REGISTRY}/ccv/tp/support/echo-server:${BUILD_VERSION} ./echo-server
    - docker push ${CCTP_REGISTRY}/ccv/tp/support/echo-server:${BUILD_VERSION}
    - docker build -t ${CCTP_REGISTRY}/ccv/tp/support/call-generator:${BUILD_VERSION} ./call-generator
    - docker push ${CCTP_REGISTRY}/ccv/tp/support/call-generator:${BUILD_VERSION}
    - docker build -t ${CCTP_REGISTRY}/ccv/tp/support/log-collector:${BUILD_VERSION} ./log-collector
    - docker push ${CCTP_REGISTRY}/ccv/tp/support/log-collector:${BUILD_VERSION}
