.general:
  tags:
    - docker
    - linux
    - ansible
    - swarm

variables:
  DOCKER_REGISTRY: 'cm-registry.ccveu.local:5000'
  CCTP_REGISTRY: 'cm-registry.ccveu.local:5002'
  BUILD_TAG: '0.5.0'
  BUILD_VERSION: "${BUILD_TAG}.${CI_COMMIT_SHORT_SHA}"
  GIT_SUBMODULE_STRATEGY: recursive

image: ${DOCKER_REGISTRY}/cm/docker-gitlab-images/gitlab-dind-make:latest

build:
  stage: build
  script:
    - echo ${CI_COMMIT_SHORT_SHA}
    - echo ${BUILD_VERSION}
    - for image in (server log-collector call-generator)
      do
        docker build -t ${CCTP_REGISTRY}/ccv/tp/support/$image:${BUILD_VERSION} ./$image
        docker push ${CCTP_REGISTRY}/ccv/tp/support/$image:${BUILD_VERSION}
      done
