---
version: "3.1"
services:
    srv:
        image: server:latest
        build: 
            context: ./server
        ports: 
            - 8080:8080
        environment:
            - "PORT=8080"
            - "ERRLOG=/home/web/log/error.log"
            - "ACCESSLOG=/home/web/log/access.log"
            - 'LOGFORMAT="%(h)s %(l)s %(t)s %({Server-IP}o)s %(l)s %(r)s %(s)s %(b)s %(a)s"'
            - "LOGLVL=INFO"
            - "SECRET_KEY=DockerComposeSecret"
        volumes: 
            - srv-logs:/home/web/log
        # deploy:
        #     replicas: 3
        #     # resources:
        #     #     limits:
        #     #         memory: 500M
        #     # restart_policy:
        #     #     condition: on-failure
        #     #     max_attempts: 3
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost"]
            interval: 1m30s
            timeout: 10s
            retries: 3
        networks:
            - srv-net 
    call-gen:
        image: call-gen:latest
        build: 
            context: ./call-generator
        environment:
            - "SERVER=srv"
            - "SRV_PATH=/api/echo"
            - "PORT=8080"
            - "LOGFILE=/home/web/log/call-gen.log"
        volumes:
            - srv-logs:/home/web/log
        networks:
            - srv-net
    log-collector:
        image: collector:latest
        build: 
            context: ./call-generator
        environment:
            - "ERRLOG=/home/web/log/error.log"
            - "ACCESSLOG=/home/web/log/access.log"
        volumes:
            - srv-logs:/home/web/log
        networks:
            - srv-net
volumes:
    srv-logs:
networks:
    srv-net: