---
version: "3.7"
services:
    srv:
        image: cm-registry.ccveu.local:5002/ccv/tp/support/echo-server:latest
        environment:
            - "PORT=8080"
            - "ERRLOG=/home/web/log/error.log"
            - "ACCESSLOG=/home/web/log/access.log"
            - 'LOGFORMAT="%(h)s %(l)s %(t)s %({Server-IP}o)s %(l)s %(r)s %(s)s %(b)s %(a)s"'
            - "LOGLVL=INFO"
            - "SECRET_KEY=DockerComposeSecret"
        ports: 
            - 8080:8080/tcp
        volumes: 
            - app-logs:/home/web/log
        secrets:
            - my_secret_key
        configs:
            - srv-config
        deploy:
            replicas: 1
            resources:
                limits:
                    memory: 100M
            restart_policy:
                condition: on-failure
                max_attempts: 3
            update_config:
                parallelism: 1
                delay: 10s
                failure_action: rollback
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/api/echo"]
            interval: 1m30s
            timeout: 10s
            retries: 3
        networks:
            - local-net 
    
    call-gen:
        image: cm-registry.ccveu.local:5002/ccv/tp/support/call-generator:latest
        environment:
            - "SERVER=srv"
            - "SRV_PATH=/api/echo"
            - "PORT=8080"
            - "LOGFILE=/home/web/log/call-gen.log"
        volumes:
            - app-logs:/home/web/log
        secrets:
            - my_secret_key
        deploy:
            replicas: 1
            resources:
                limits:
                    memory: 10M
            restart_policy:
                condition: on-failure
                max_attempts: 3
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback
        networks:
            - local-net

    log-collector:
        image: cm-registry.ccveu.local:5002/ccv/tp/support/log-collector:latest
        environment:
            - "ERRLOG=/home/web/log/error.log"
            - "ACCESSLOG=/home/web/log/access.log"
        ports: 
            - 8081:8081/tcp
        volumes:
            - app-logs:/home/web/log
        deploy:
            replicas: 1
            resources:
                limits:
                    memory: 100M
            restart_policy:
                condition: on-failure
                # max_attempts: 3
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback
        networks:
            - local-net

volumes:
    app-logs:
networks:
    local-net:
secrets:
    my_secret_key:
        external: true
configs:
    srv-config:
        file: ./server/srv-config.yml
