---
version: "3.1"
services:
    demo-server:
        image: demoserver:0.1
        ports: 
            - 8080:8080
        volumes: 
            - srv-logs:/home/web/log
        deploy:
            replicas: 2
volumes:
    srv-logs:
networks:
    demo-net: