---
version: "3.1"
services:
    srv:
        image: cgerull/demo-server:latest
        ports: 
            - 8080:8080
        volumes: 
            - srv-logs:/home/web/log
        deploy:
            replicas: 3
            # resources:
            #     limits:
            #         memory: 500M
            # restart_policy:
            #     condition: on-failure
            #     max_attempts: 3
        # healthcheck:
        #     test: ["CMD", "curl", "-f", "http://localhost"]
        #     interval: 1m30s
        #     timeout: 10s
        #     retries: 3
        networks:
            - srv-net 
volumes:
    srv-logs:
networks:
    srv-net: